services:
  minio:
    image: minio/minio:latest
    container_name: calcpad-minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: calcpad-admin
      MINIO_ROOT_PASSWORD: calcpad-password-123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


  calcpad-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    container_name: calcpad-api
    ports:
      - "${API_PORT:-5000}:5000"
      - "${DEBUG_PORT:-9229}:9229"
    volumes:
      - calcpad-db:/app/data
      - ./api/src:/app/src:ro
    depends_on:
      - minio
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=5000
      - DATABASE_PATH=/app/data/calcpad.db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=calcpad-admin
      - MINIO_SECRET_KEY=calcpad-password-123
      - MINIO_BUCKET_NAME=calcpad-storage
      - MINIO_USE_SSL=false
      - JWT_SECRET=calcpad-jwt-secret-key-change-in-production-minimum-32-characters
      - JWT_EXPIRY_HOURS=24
      - JWT_ISSUER=CalcpadS3
      - JWT_AUDIENCE=CalcpadClients
      - AUTH_PROVIDER=Local
      - LOCAL_AUTH_ENABLED=true
      - ALLOW_USER_REGISTRATION=true
      - REQUIRE_EMAIL_CONFIRMATION=false
      # Override auth provider via environment variables
      # - AUTH_PROVIDER=OIDC
      # - OIDC_ENABLED=true
      # - OIDC_AUTHORITY=https://your-sso-provider.com
      # - OIDC_CLIENT_ID=calcpad-client
      # - OIDC_CLIENT_SECRET=your-client-secret

  calcpad-viewer:
    build:
      context: ./viewer
      dockerfile: Dockerfile
    container_name: calcpad-viewer
    ports:
      - "${VIEWER_PORT:-3000}:80"
    depends_on:
      - calcpad-api
    environment:
      - API_BASE_URL=http://localhost:${API_PORT:-5000}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: calcpad-cloudflared
    profiles:
      - tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - calcpad-api
      - calcpad-viewer
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - default

volumes:
  minio-data:
    driver: local
  calcpad-db:
    driver: local